version: '3'

services:
  nginx:
    image: "nginx:latest"
    volumes:
      - /home/roye/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - "public-net-1"
  netflixmoviecatalog:
    build: .
    ports:
      - "8080:8080"
    networks:
      - "privet-net-1"
  netflixfronted:
    build: /home/roye/NetflixFrontend
    environment:
      - MOVIE_CATALOG_SERVICE=http://netflixmoviecatalog:8080
    ports:
      - "3000:3000"
    networks:
      - "public-net-1"
      - "privet-net-1"

networks:
  public-net-1:
     driver: bridge
  privet-net-1:
     driver: bridge
  privet-net-2:
    driver: bridge