name: Netflix Movie Catalog Service Deployment

on:
  push:
    branches:
      - main

env:
  EC2_PUBLIC_IP: "13.60.61.113"  # TODO replace to your EC2 instance public IP
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  # TODO define this secret in your GitHub repo settings

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          IMAGE_NAME=royeb/netflix_movie_catalog:${{ github.run_number }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
      - name: SSH to EC2 instance
        run: |
          echo "$SSH_PRIVATE_KEY" > roye-key.pem
          chmod 400 roye-key.pem

          # Copy the files from the current wrok dir into the EC2 instance, under `~/app`.
          scp -o StrictHostKeyChecking=no -i roye-key.pem deploy.sh ubuntu@$EC2_PUBLIC_IP:~/app

          # Connect to your EC2 instance and execute the `deploy.sh` script (this script is part of the repo files).
          # You need to implement the `deploy.sh` script yourself.
          #
          # Upon completion, the NetflixMovieCatalog app should be running with its newer version.
          # To keep the app running in the background independently on the terminal session you are logging to, configure it as a Linux service.

          ssh -i roye-key.pem ubuntu@$EC2_PUBLIC_IP "bash /home/ubuntu/app/deploy.sh"
          #

